# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\explorer\explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Explorer(object):
    def setupUi(self, Explorer):
        Explorer.setObjectName("Explorer")
        Explorer.resize(1000, 618)

        self.retranslateUi(Explorer)
        QtCore.QMetaObject.connectSlotsByName(Explorer)

    def retranslateUi(self, Explorer):
        _translate = QtCore.QCoreApplication.translate
        Explorer.setWindowTitle(_translate("Explorer", "Functional Minecraft Launcher"))
