# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\settingeditor\settingcard\setting_adder.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingAdder(object):
    def setupUi(self, SettingAdder):
        SettingAdder.setObjectName("SettingAdder")
        SettingAdder.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(SettingAdder)
        self.gridLayout.setObjectName("gridLayout")
        self.value_editor = SettingJsonEditor(parent=SettingAdder)
        self.value_editor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.value_editor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.value_editor.setObjectName("value_editor")
        self.gridLayout.addWidget(self.value_editor, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingAdder)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 1, 1, 1)
        self.index_editor = SpinBox(parent=SettingAdder)
        self.index_editor.setObjectName("index_editor")
        self.gridLayout.addWidget(self.index_editor, 0, 1, 1, 1)
        self.attr_editor = SettingJsonEditor(parent=SettingAdder)
        self.attr_editor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.attr_editor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.attr_editor.setObjectName("attr_editor")
        self.gridLayout.addWidget(self.attr_editor, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=SettingAdder)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=SettingAdder)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=SettingAdder)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.key_editor = LineEdit(parent=SettingAdder)
        self.key_editor.setObjectName("key_editor")
        self.gridLayout.addWidget(self.key_editor, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=SettingAdder)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)

        self.retranslateUi(SettingAdder)
        self.buttonBox.accepted.connect(SettingAdder.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingAdder.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingAdder)

    def retranslateUi(self, SettingAdder):
        _translate = QtCore.QCoreApplication.translate
        SettingAdder.setWindowTitle(_translate("SettingAdder", "添加值"))
        self.label.setText(_translate("SettingAdder", "值"))
        self.label_2.setText(_translate("SettingAdder", "属性"))
        self.label_3.setText(_translate("SettingAdder", "索引"))
        self.label_4.setText(_translate("SettingAdder", "键"))
from json_editor import SettingJsonEditor
from qfluentwidgets import LineEdit, SpinBox
