# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\helpviewer\help_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpViewer(object):
    def setupUi(self, HelpViewer):
        HelpViewer.setObjectName("HelpViewer")
        HelpViewer.resize(1000, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(HelpViewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(parent=HelpViewer)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.help_index = TreeView(parent=self.splitter)
        self.help_index.setObjectName("help_index")
        self.help_index.header().setVisible(False)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.page_stack = QtWidgets.QStackedWidget(parent=self.gridLayoutWidget)
        self.page_stack.setObjectName("page_stack")
        self.gridLayout.addWidget(self.page_stack, 1, 0, 1, 2)
        self.detach_button = PushButton(parent=self.gridLayoutWidget)
        self.detach_button.setObjectName("detach_button")
        self.gridLayout.addWidget(self.detach_button, 0, 1, 1, 1)
        self.tabbar = TabBar(parent=self.gridLayoutWidget)
        self.tabbar.setObjectName("tabbar")
        self.gridLayout.addWidget(self.tabbar, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(HelpViewer)
        QtCore.QMetaObject.connectSlotsByName(HelpViewer)

    def retranslateUi(self, HelpViewer):
        _translate = QtCore.QCoreApplication.translate
        HelpViewer.setWindowTitle(_translate("HelpViewer", "帮助"))
        self.detach_button.setText(_translate("HelpViewer", "分离"))
from qfluentwidgets import PushButton, TabBar, TreeView
