# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemanager\modmanager\mod_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModManager(object):
    def setupUi(self, ModManager):
        ModManager.setObjectName("ModManager")
        ModManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModManager)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=ModManager)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.enable_button = PushButton(parent=self.page)
        self.enable_button.setObjectName("enable_button")
        self.gridLayout_2.addWidget(self.enable_button, 1, 1, 1, 1)
        self.statistics = QtWidgets.QLabel(parent=self.page)
        self.statistics.setText("")
        self.statistics.setObjectName("statistics")
        self.gridLayout_2.addWidget(self.statistics, 1, 5, 1, 1)
        self.disable_button = PushButton(parent=self.page)
        self.disable_button.setObjectName("disable_button")
        self.gridLayout_2.addWidget(self.disable_button, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 4, 1, 1)
        self.del_button = PushButton(parent=self.page)
        self.del_button.setObjectName("del_button")
        self.gridLayout_2.addWidget(self.del_button, 1, 3, 1, 1)
        self.refresh_button = PushButton(parent=self.page)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout_2.addWidget(self.refresh_button, 1, 0, 1, 1)
        self.search_input = SearchLineEdit(parent=self.page)
        self.search_input.setObjectName("search_input")
        self.gridLayout_2.addWidget(self.search_input, 0, 0, 1, 7)
        self.mod_list = ListWidget(parent=self.page)
        self.mod_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.mod_list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.mod_list.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.mod_list.setObjectName("mod_list")
        self.gridLayout_2.addWidget(self.mod_list, 2, 0, 1, 7)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(ModManager)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ModManager)

    def retranslateUi(self, ModManager):
        _translate = QtCore.QCoreApplication.translate
        ModManager.setWindowTitle(_translate("ModManager", "模组管理器"))
        self.label.setText(_translate("ModManager", "该实例不支持模组"))
        self.enable_button.setText(_translate("ModManager", "启用"))
        self.disable_button.setText(_translate("ModManager", "禁用"))
        self.label_2.setText(_translate("ModManager", "统计:"))
        self.del_button.setText(_translate("ModManager", "删除"))
        self.refresh_button.setText(_translate("ModManager", "刷新"))
from qfluentwidgets import ListWidget, PushButton, SearchLineEdit
