# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\addressmanager\address_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddressManager(object):
    def setupUi(self, AddressManager):
        AddressManager.setObjectName("AddressManager")
        AddressManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(AddressManager)
        self.gridLayout.setObjectName("gridLayout")
        self.viewer = TableWidget(parent=AddressManager)
        self.viewer.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.viewer.setRowCount(0)
        self.viewer.setColumnCount(2)
        self.viewer.setObjectName("viewer")
        self.viewer.horizontalHeader().setSortIndicatorShown(False)
        self.viewer.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.viewer, 0, 0, 1, 1)

        self.retranslateUi(AddressManager)
        QtCore.QMetaObject.connectSlotsByName(AddressManager)

    def retranslateUi(self, AddressManager):
        _translate = QtCore.QCoreApplication.translate
        AddressManager.setWindowTitle(_translate("AddressManager", "网址管理器"))
from qfluentwidgets import TableWidget
