# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemanager\game_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameManager(object):
    def setupUi(self, GameManager):
        GameManager.setObjectName("GameManager")
        GameManager.resize(1000, 618)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GameManager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigation_bar = NavigationBar(parent=GameManager)
        self.navigation_bar.setObjectName("navigation_bar")
        self.horizontalLayout.addWidget(self.navigation_bar)
        self.stack = QtWidgets.QStackedWidget(parent=GameManager)
        self.stack.setObjectName("stack")
        self.horizontalLayout.addWidget(self.stack)

        self.retranslateUi(GameManager)
        QtCore.QMetaObject.connectSlotsByName(GameManager)

    def retranslateUi(self, GameManager):
        _translate = QtCore.QCoreApplication.translate
        GameManager.setWindowTitle(_translate("GameManager", "游戏管理器"))
from qfluentwidgets import NavigationBar
