# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemonitor\game_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameMonitor(object):
    def setupUi(self, GameMonitor):
        GameMonitor.setObjectName("GameMonitor")
        GameMonitor.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameMonitor)
        self.gridLayout.setObjectName("gridLayout")
        self.kill_button = PushButton(parent=GameMonitor)
        self.kill_button.setObjectName("kill_button")
        self.gridLayout.addWidget(self.kill_button, 2, 3, 1, 1)
        self.performance = QtWidgets.QLabel(parent=GameMonitor)
        self.performance.setText("")
        self.performance.setObjectName("performance")
        self.gridLayout.addWidget(self.performance, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.auto_scroll = CheckBox(parent=GameMonitor)
        self.auto_scroll.setChecked(True)
        self.auto_scroll.setObjectName("auto_scroll")
        self.gridLayout.addWidget(self.auto_scroll, 2, 2, 1, 1)
        self.log_viewer = QtWidgets.QListWidget(parent=GameMonitor)
        self.log_viewer.setObjectName("log_viewer")
        self.gridLayout.addWidget(self.log_viewer, 1, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.counter_layout = QtWidgets.QHBoxLayout()
        self.counter_layout.setObjectName("counter_layout")
        self.horizontalLayout.addLayout(self.counter_layout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)

        self.retranslateUi(GameMonitor)
        QtCore.QMetaObject.connectSlotsByName(GameMonitor)

    def retranslateUi(self, GameMonitor):
        _translate = QtCore.QCoreApplication.translate
        GameMonitor.setWindowTitle(_translate("GameMonitor", "游戏监视器"))
        self.kill_button.setText(_translate("GameMonitor", "结束游戏"))
        self.auto_scroll.setText(_translate("GameMonitor", "自动滚动"))
from qfluentwidgets import CheckBox, PushButton
