# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\nbtviewer\nbt_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NBTViewer(object):
    def setupUi(self, NBTViewer):
        NBTViewer.setObjectName("NBTViewer")
        NBTViewer.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(NBTViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.nbt = TreeView(parent=NBTViewer)
        self.nbt.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.nbt.setIndentation(16)
        self.nbt.setObjectName("nbt")
        self.gridLayout.addWidget(self.nbt, 0, 0, 1, 1)

        self.retranslateUi(NBTViewer)
        QtCore.QMetaObject.connectSlotsByName(NBTViewer)

    def retranslateUi(self, NBTViewer):
        _translate = QtCore.QCoreApplication.translate
        NBTViewer.setWindowTitle(_translate("NBTViewer", "NBT查看器"))
from qfluentwidgets import TreeView
