# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\news\news_entry.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewsEntry(object):
    def setupUi(self, NewsEntry):
        NewsEntry.setObjectName("NewsEntry")
        NewsEntry.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(NewsEntry)
        self.gridLayout.setObjectName("gridLayout")
        self.image_label = QtWidgets.QLabel(parent=NewsEntry)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=NewsEntry)
        font = QtGui.QFont()
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setText("")
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.text_label = QtWidgets.QLabel(parent=NewsEntry)
        self.text_label.setText("")
        self.text_label.setScaledContents(False)
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        self.verticalLayout.addWidget(self.text_label)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.date_label = QtWidgets.QLabel(parent=NewsEntry)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.date_label.setFont(font)
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.date_label.setWordWrap(True)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 3, 0, 1, 1)

        self.retranslateUi(NewsEntry)
        QtCore.QMetaObject.connectSlotsByName(NewsEntry)

    def retranslateUi(self, NewsEntry):
        _translate = QtCore.QCoreApplication.translate
        NewsEntry.setWindowTitle(_translate("NewsEntry", "NewsEntry"))
