# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\news\news.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_News(object):
    def setupUi(self, News):
        News.setObjectName("News")
        News.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(News)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=News)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 980, 598))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gl_entries = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gl_entries.setObjectName("gl_entries")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(News)
        QtCore.QMetaObject.connectSlotsByName(News)

    def retranslateUi(self, News):
        _translate = QtCore.QCoreApplication.translate
        News.setWindowTitle(_translate("News", "新闻"))
