# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemanager\overviewer\icon_selector.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IconSelector(object):
    def setupUi(self, IconSelector):
        IconSelector.setObjectName("IconSelector")
        IconSelector.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(IconSelector)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=IconSelector)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.pushButton = PushButton(parent=IconSelector)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.icon_list = ListWidget(parent=IconSelector)
        self.icon_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.icon_list.setIconSize(QtCore.QSize(32, 32))
        self.icon_list.setMovement(QtWidgets.QListView.Movement.Static)
        self.icon_list.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.icon_list.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        self.icon_list.setWordWrap(True)
        self.icon_list.setObjectName("icon_list")
        self.gridLayout.addWidget(self.icon_list, 0, 0, 1, 3)

        self.retranslateUi(IconSelector)
        self.buttonBox.accepted.connect(IconSelector.accept) # type: ignore
        self.buttonBox.rejected.connect(IconSelector.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(IconSelector)

    def retranslateUi(self, IconSelector):
        _translate = QtCore.QCoreApplication.translate
        IconSelector.setWindowTitle(_translate("IconSelector", "图标选择"))
        self.pushButton.setText(_translate("IconSelector", "添加"))
from qfluentwidgets import ListWidget, PushButton
