# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemanager\overviewer\overviewer.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Overviewer(object):
    def setupUi(self, Overviewer):
        Overviewer.setObjectName("Overviewer")
        Overviewer.resize(1000, 618)
        self.verticalLayout = QtWidgets.QVBoxLayout(Overviewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.browser = GroupHeaderCardWidget(parent=Overviewer)
        self.browser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.browser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.browser.setObjectName("browser")
        self.verticalLayout.addWidget(self.browser)
        self.time_summary = QtWidgets.QLabel(parent=Overviewer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_summary.setFont(font)
        self.time_summary.setText("")
        self.time_summary.setObjectName("time_summary")
        self.verticalLayout.addWidget(self.time_summary)
        self.time_record_view = TableWidget(parent=Overviewer)
        self.time_record_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.time_record_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.time_record_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.time_record_view.setObjectName("time_record_view")
        self.time_record_view.setColumnCount(3)
        self.time_record_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.time_record_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_record_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_record_view.setHorizontalHeaderItem(2, item)
        self.time_record_view.horizontalHeader().setCascadingSectionResizes(False)
        self.time_record_view.horizontalHeader().setSortIndicatorShown(False)
        self.time_record_view.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.time_record_view)

        self.retranslateUi(Overviewer)
        QtCore.QMetaObject.connectSlotsByName(Overviewer)

    def retranslateUi(self, Overviewer):
        _translate = QtCore.QCoreApplication.translate
        Overviewer.setWindowTitle(_translate("Overviewer", "概览"))
        item = self.time_record_view.horizontalHeaderItem(0)
        item.setText(_translate("Overviewer", "开始时间"))
        item = self.time_record_view.horizontalHeaderItem(1)
        item.setText(_translate("Overviewer", "结束时间"))
        item = self.time_record_view.horizontalHeaderItem(2)
        item.setText(_translate("Overviewer", "时长"))
from qfluentwidgets import GroupHeaderCardWidget, TableWidget
