# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamemanager\overviewer\overviewer.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Overviewer(object):
    def setupUi(self, Overviewer):
        Overviewer.setObjectName("Overviewer")
        Overviewer.resize(1000, 618)
        self.verticalLayout = QtWidgets.QVBoxLayout(Overviewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.browser = GroupHeaderCardWidget(parent=Overviewer)
        self.browser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.browser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.browser.setObjectName("browser")
        self.verticalLayout.addWidget(self.browser)
        spacerItem = QtWidgets.QSpacerItem(20, 581, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Overviewer)
        QtCore.QMetaObject.connectSlotsByName(Overviewer)

    def retranslateUi(self, Overviewer):
        _translate = QtCore.QCoreApplication.translate
        Overviewer.setWindowTitle(_translate("Overviewer", "概览"))
from qfluentwidgets import GroupHeaderCardWidget
