# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\settingeditor\setting_editor.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingEditor(object):
    def setupUi(self, SettingEditor):
        SettingEditor.setObjectName("SettingEditor")
        SettingEditor.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(SettingEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.search_input = SearchLineEdit(parent=SettingEditor)
        self.search_input.setObjectName("search_input")
        self.gridLayout.addWidget(self.search_input, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(parent=SettingEditor)
        self.splitter.setStyleSheet("QSplitter::handle{\n"
"    background-color:rgb(235,235,235);\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.navigation = TreeView(parent=self.splitter)
        self.navigation.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.navigation.setIndentation(16)
        self.navigation.setSortingEnabled(False)
        self.navigation.setWordWrap(True)
        self.navigation.setObjectName("navigation")
        self.navigation.header().setVisible(False)
        self.edit_area = ScrollArea(parent=self.splitter)
        self.edit_area.setWidgetResizable(True)
        self.edit_area.setObjectName("edit_area")
        self.edit_area_content = QtWidgets.QWidget()
        self.edit_area_content.setGeometry(QtCore.QRect(0, 0, 69, 572))
        self.edit_area_content.setObjectName("edit_area_content")
        self.edit_layout = QtWidgets.QVBoxLayout(self.edit_area_content)
        self.edit_layout.setContentsMargins(0, 0, 0, 0)
        self.edit_layout.setObjectName("edit_layout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.edit_layout.addItem(spacerItem)
        self.edit_area.setWidget(self.edit_area_content)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(SettingEditor)
        QtCore.QMetaObject.connectSlotsByName(SettingEditor)

    def retranslateUi(self, SettingEditor):
        _translate = QtCore.QCoreApplication.translate
        SettingEditor.setWindowTitle(_translate("SettingEditor", "设置"))
from qfluentwidgets import ScrollArea, SearchLineEdit, TreeView
