# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamedownloader\fabric_selector.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FabricSelector(object):
    def setupUi(self, FabricSelector):
        FabricSelector.setObjectName("FabricSelector")
        FabricSelector.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(FabricSelector)
        self.gridLayout.setObjectName("gridLayout")
        self.version_filter = SearchLineEdit(parent=FabricSelector)
        self.version_filter.setObjectName("version_filter")
        self.gridLayout.addWidget(self.version_filter, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=FabricSelector)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 572))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewer_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.viewer_layout.setObjectName("viewer_layout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.viewer_layout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(FabricSelector)
        QtCore.QMetaObject.connectSlotsByName(FabricSelector)

    def retranslateUi(self, FabricSelector):
        _translate = QtCore.QCoreApplication.translate
        FabricSelector.setWindowTitle(_translate("FabricSelector", "Fabric选择"))
from qfluentwidgets import SearchLineEdit
