# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamedownloader\game_downloader.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameDownloader(object):
    def setupUi(self, GameDownloader):
        GameDownloader.setObjectName("GameDownloader")
        GameDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameDownloader)
        self.gridLayout.setObjectName("gridLayout")
        self.download_button = PushButton(parent=GameDownloader)
        self.download_button.setObjectName("download_button")
        self.gridLayout.addWidget(self.download_button, 0, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_original = TransparentTogglePushButton(parent=GameDownloader)
        self.select_original.setObjectName("select_original")
        self.horizontalLayout.addWidget(self.select_original)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 6)
        self.instance_name = LineEdit(parent=GameDownloader)
        self.instance_name.setObjectName("instance_name")
        self.gridLayout.addWidget(self.instance_name, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(parent=GameDownloader)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.selector_stack = QtWidgets.QStackedWidget(parent=GameDownloader)
        self.selector_stack.setObjectName("selector_stack")
        self.gridLayout.addWidget(self.selector_stack, 3, 0, 1, 6)
        self.download_install_button = PushButton(parent=GameDownloader)
        self.download_install_button.setObjectName("download_install_button")
        self.gridLayout.addWidget(self.download_install_button, 0, 5, 1, 1)
        self.auto_set_instance_name = CheckBox(parent=GameDownloader)
        self.auto_set_instance_name.setChecked(True)
        self.auto_set_instance_name.setTristate(False)
        self.auto_set_instance_name.setObjectName("auto_set_instance_name")
        self.gridLayout.addWidget(self.auto_set_instance_name, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pivot = SegmentedWidget(parent=GameDownloader)
        self.pivot.setObjectName("pivot")
        self.horizontalLayout_2.addWidget(self.pivot)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 6)

        self.retranslateUi(GameDownloader)
        QtCore.QMetaObject.connectSlotsByName(GameDownloader)

    def retranslateUi(self, GameDownloader):
        _translate = QtCore.QCoreApplication.translate
        GameDownloader.setWindowTitle(_translate("GameDownloader", "游戏下载器"))
        self.download_button.setText(_translate("GameDownloader", "下载"))
        self.select_original.setText(_translate("GameDownloader", "原版"))
        self.label.setText(_translate("GameDownloader", "游戏实例名称"))
        self.download_install_button.setText(_translate("GameDownloader", "下载并安装"))
        self.auto_set_instance_name.setText(_translate("GameDownloader", "自动设置实例名称"))
from qfluentwidgets import CheckBox, LineEdit, PushButton, SegmentedWidget, TransparentTogglePushButton
