# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\gamedownloader\original_selector.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OriginalSelector(object):
    def setupUi(self, OriginalSelector):
        OriginalSelector.setObjectName("OriginalSelector")
        OriginalSelector.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(OriginalSelector)
        self.gridLayout.setObjectName("gridLayout")
        self.version_filter = SearchLineEdit(parent=OriginalSelector)
        self.version_filter.setObjectName("version_filter")
        self.gridLayout.addWidget(self.version_filter, 0, 0, 1, 1)
        self.type_filter = ComboBox(parent=OriginalSelector)
        self.type_filter.setIconSize(QtCore.QSize(16, 16))
        self.type_filter.setObjectName("type_filter")
        self.type_filter.addItem("")
        self.type_filter.addItem("")
        self.type_filter.addItem("")
        self.type_filter.addItem("")
        self.gridLayout.addWidget(self.type_filter, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=OriginalSelector)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 568))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewer_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.viewer_layout.setObjectName("viewer_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 2)

        self.retranslateUi(OriginalSelector)
        self.type_filter.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OriginalSelector)

    def retranslateUi(self, OriginalSelector):
        _translate = QtCore.QCoreApplication.translate
        OriginalSelector.setWindowTitle(_translate("OriginalSelector", "原版选择"))
        self.type_filter.setItemText(0, _translate("OriginalSelector", "全部"))
        self.type_filter.setItemText(1, _translate("OriginalSelector", "正式版"))
        self.type_filter.setItemText(2, _translate("OriginalSelector", "快照"))
        self.type_filter.setItemText(3, _translate("OriginalSelector", "远古版"))
from qfluentwidgets import ComboBox, SearchLineEdit
