# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\taskmanager\task_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskManager(object):
    def setupUi(self, TaskManager):
        TaskManager.setObjectName("TaskManager")
        TaskManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(TaskManager)
        self.gridLayout.setObjectName("gridLayout")
        self.task_view = TreeWidget(parent=TaskManager)
        self.task_view.setColumnCount(4)
        self.task_view.setObjectName("task_view")
        self.gridLayout.addWidget(self.task_view, 0, 0, 1, 1)

        self.retranslateUi(TaskManager)
        QtCore.QMetaObject.connectSlotsByName(TaskManager)

    def retranslateUi(self, TaskManager):
        _translate = QtCore.QCoreApplication.translate
        TaskManager.setWindowTitle(_translate("TaskManager", "任务管理器"))
        self.task_view.headerItem().setText(0, _translate("TaskManager", "id"))
        self.task_view.headerItem().setText(1, _translate("TaskManager", "名称"))
        self.task_view.headerItem().setText(2, _translate("TaskManager", "进度"))
        self.task_view.headerItem().setText(3, _translate("TaskManager", "当前工作"))
from qfluentwidgets import TreeWidget
