# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\updater\updater.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Updater(object):
    def setupUi(self, Updater):
        Updater.setObjectName("Updater")
        Updater.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Updater)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Updater)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.content = TextEdit(parent=self.page_2)
        self.content.setReadOnly(True)
        self.content.setObjectName("content")
        self.gridLayout_3.addWidget(self.content, 0, 0, 1, 3)
        self.download_button = PushButton(parent=self.page_2)
        self.download_button.setObjectName("download_button")
        self.gridLayout_3.addWidget(self.download_button, 1, 1, 1, 1)
        self.update_button = PushButton(parent=self.page_2)
        self.update_button.setObjectName("update_button")
        self.gridLayout_3.addWidget(self.update_button, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Updater)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Updater)

    def retranslateUi(self, Updater):
        _translate = QtCore.QCoreApplication.translate
        Updater.setWindowTitle(_translate("Updater", "更新"))
        self.download_button.setText(_translate("Updater", "下载"))
        self.update_button.setText(_translate("Updater", "下载并更新"))
from qfluentwidgets import PushButton, TextEdit
