# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\javamanager\java_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_JavaManager(object):
    def setupUi(self, JavaManager):
        JavaManager.setObjectName("JavaManager")
        JavaManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(JavaManager)
        self.gridLayout.setObjectName("gridLayout")
        self.java_layout = QtWidgets.QVBoxLayout()
        self.java_layout.setObjectName("java_layout")
        self.gridLayout.addLayout(self.java_layout, 0, 0, 1, 1)

        self.retranslateUi(JavaManager)
        QtCore.QMetaObject.connectSlotsByName(JavaManager)

    def retranslateUi(self, JavaManager):
        _translate = QtCore.QCoreApplication.translate
        JavaManager.setWindowTitle(_translate("JavaManager", "Java管理器"))
