# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\accountmanager\authlib_injector_signiner.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthlibInjectorSignIner(object):
    def setupUi(self, AuthlibInjectorSignIner):
        AuthlibInjectorSignIner.setObjectName("AuthlibInjectorSignIner")
        AuthlibInjectorSignIner.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(AuthlibInjectorSignIner)
        self.gridLayout.setObjectName("gridLayout")
        self.password = PasswordLineEdit(parent=AuthlibInjectorSignIner)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.server_name = QtWidgets.QLabel(parent=AuthlibInjectorSignIner)
        self.server_name.setObjectName("server_name")
        self.gridLayout.addWidget(self.server_name, 0, 1, 1, 1)
        self.register_link = HyperlinkButton(parent=AuthlibInjectorSignIner)
        self.register_link.setObjectName("register_link")
        self.gridLayout.addWidget(self.register_link, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=AuthlibInjectorSignIner)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=AuthlibInjectorSignIner)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.homepage_link = HyperlinkButton(parent=AuthlibInjectorSignIner)
        self.homepage_link.setObjectName("homepage_link")
        self.gridLayout.addWidget(self.homepage_link, 0, 3, 1, 1)
        self.username = LineEdit(parent=AuthlibInjectorSignIner)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 2, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AuthlibInjectorSignIner)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 3, 1, 2)

        self.retranslateUi(AuthlibInjectorSignIner)
        self.buttonBox.accepted.connect(AuthlibInjectorSignIner.accept) # type: ignore
        self.buttonBox.rejected.connect(AuthlibInjectorSignIner.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AuthlibInjectorSignIner)

    def retranslateUi(self, AuthlibInjectorSignIner):
        _translate = QtCore.QCoreApplication.translate
        AuthlibInjectorSignIner.setWindowTitle(_translate("AuthlibInjectorSignIner", "外置登录"))
        self.server_name.setText(_translate("AuthlibInjectorSignIner", "认证服务器: "))
        self.register_link.setText(_translate("AuthlibInjectorSignIner", "注册"))
        self.label.setText(_translate("AuthlibInjectorSignIner", "邮箱"))
        self.label_2.setText(_translate("AuthlibInjectorSignIner", "密码"))
        self.homepage_link.setText(_translate("AuthlibInjectorSignIner", "主页"))
from qfluentwidgets import HyperlinkButton, LineEdit, PasswordLineEdit
