# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\accountmanager\account_manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AccountManager(object):
    def setupUi(self, AccountManager):
        AccountManager.setObjectName("AccountManager")
        AccountManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(AccountManager)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=AccountManager)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.account_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.account_layout.setObjectName("account_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.account_layout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 2)
        self.login_method_panel = NavigationPanel(parent=AccountManager)
        self.login_method_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.login_method_panel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_method_panel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_method_panel.setObjectName("login_method_panel")
        self.gridLayout.addWidget(self.login_method_panel, 0, 0, 1, 1)

        self.retranslateUi(AccountManager)
        QtCore.QMetaObject.connectSlotsByName(AccountManager)

    def retranslateUi(self, AccountManager):
        _translate = QtCore.QCoreApplication.translate
        AccountManager.setWindowTitle(_translate("AccountManager", "账号管理"))
from qfluentwidgets import NavigationPanel
