# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\accountmanager\authlib_injector_adder.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthlibInjectorAdder(object):
    def setupUi(self, AuthlibInjectorAdder):
        AuthlibInjectorAdder.setObjectName("AuthlibInjectorAdder")
        AuthlibInjectorAdder.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(AuthlibInjectorAdder)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=AuthlibInjectorAdder)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.url = LineEdit(parent=AuthlibInjectorAdder)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AuthlibInjectorAdder)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(AuthlibInjectorAdder)
        self.buttonBox.accepted.connect(AuthlibInjectorAdder.accept) # type: ignore
        self.buttonBox.rejected.connect(AuthlibInjectorAdder.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AuthlibInjectorAdder)

    def retranslateUi(self, AuthlibInjectorAdder):
        _translate = QtCore.QCoreApplication.translate
        AuthlibInjectorAdder.setWindowTitle(_translate("AuthlibInjectorAdder", "添加外置登录服务器"))
        self.label.setText(_translate("AuthlibInjectorAdder", "网址"))
from qfluentwidgets import LineEdit
