# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\accountmanager\offline_adder.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OfflineAdder(object):
    def setupUi(self, OfflineAdder):
        OfflineAdder.setObjectName("OfflineAdder")
        OfflineAdder.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(OfflineAdder)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=OfflineAdder)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(parent=OfflineAdder)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.player_name = LineEdit(parent=OfflineAdder)
        self.player_name.setObjectName("player_name")
        self.gridLayout.addWidget(self.player_name, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=OfflineAdder)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.uuid = LineEdit(parent=OfflineAdder)
        self.uuid.setObjectName("uuid")
        self.gridLayout.addWidget(self.uuid, 1, 2, 1, 1)

        self.retranslateUi(OfflineAdder)
        self.buttonBox.accepted.connect(OfflineAdder.accept) # type: ignore
        self.buttonBox.rejected.connect(OfflineAdder.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OfflineAdder)

    def retranslateUi(self, OfflineAdder):
        _translate = QtCore.QCoreApplication.translate
        OfflineAdder.setWindowTitle(_translate("OfflineAdder", "离线账号"))
        self.label.setText(_translate("OfflineAdder", "玩家名"))
        self.label_2.setText(_translate("OfflineAdder", "UUID"))
        self.uuid.setPlaceholderText(_translate("OfflineAdder", "留空将自动生成"))
from qfluentwidgets import LineEdit
