# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\musicplayer\music_player.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(MusicPlayer)
        self.gridLayout.setObjectName("gridLayout")
        self.play_bar = StandardMediaPlayBar(parent=MusicPlayer)
        self.play_bar.setObjectName("play_bar")
        self.gridLayout.addWidget(self.play_bar, 2, 0, 1, 1)
        self.music_list = TableWidget(parent=MusicPlayer)
        self.music_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.music_list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.music_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.music_list.setColumnCount(5)
        self.music_list.setObjectName("music_list")
        self.music_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(4, item)
        self.music_list.horizontalHeader().setCascadingSectionResizes(False)
        self.music_list.horizontalHeader().setSortIndicatorShown(False)
        self.music_list.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.music_list, 0, 0, 1, 1)
        self.playing_music = QtWidgets.QLabel(parent=MusicPlayer)
        self.playing_music.setText("")
        self.playing_music.setObjectName("playing_music")
        self.gridLayout.addWidget(self.playing_music, 1, 0, 1, 1)

        self.retranslateUi(MusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "音乐播放器"))
        item = self.music_list.horizontalHeaderItem(0)
        item.setText(_translate("MusicPlayer", "标题"))
        item = self.music_list.horizontalHeaderItem(1)
        item.setText(_translate("MusicPlayer", "艺术家"))
        item = self.music_list.horizontalHeaderItem(2)
        item.setText(_translate("MusicPlayer", "唱片集"))
        item = self.music_list.horizontalHeaderItem(3)
        item.setText(_translate("MusicPlayer", "年份"))
        item = self.music_list.horizontalHeaderItem(4)
        item.setText(_translate("MusicPlayer", "路径"))
from qfluentwidgets import TableWidget
from qfluentwidgets.multimedia import StandardMediaPlayBar
