# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\resourcedownloader\modrinth_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModrinthDetail(object):
    def setupUi(self, ModrinthDetail):
        ModrinthDetail.setObjectName("ModrinthDetail")
        ModrinthDetail.resize(1000, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(ModrinthDetail)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.url_layout = QtWidgets.QHBoxLayout()
        self.url_layout.setObjectName("url_layout")
        self.gridLayout_2.addLayout(self.url_layout, 1, 0, 1, 1)
        self.result_layout = QtWidgets.QGridLayout()
        self.result_layout.setSpacing(0)
        self.result_layout.setObjectName("result_layout")
        self.gridLayout_2.addLayout(self.result_layout, 0, 0, 1, 1)
        self.version_list = ListWidget(parent=ModrinthDetail)
        self.version_list.setObjectName("version_list")
        self.gridLayout_2.addWidget(self.version_list, 2, 0, 1, 1)

        self.retranslateUi(ModrinthDetail)
        QtCore.QMetaObject.connectSlotsByName(ModrinthDetail)

    def retranslateUi(self, ModrinthDetail):
        _translate = QtCore.QCoreApplication.translate
        ModrinthDetail.setWindowTitle(_translate("ModrinthDetail", "ModrinthDetail"))
from qfluentwidgets import ListWidget
