# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\resourcedownloader\modrinth_version.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModrinthVersion(object):
    def setupUi(self, ModrinthVersion):
        ModrinthVersion.setObjectName("ModrinthVersion")
        ModrinthVersion.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModrinthVersion)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = ScrollArea(parent=ModrinthVersion)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.depend_group = HeaderCardWidget(parent=self.scrollAreaWidgetContents)
        self.depend_group.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.depend_group.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.depend_group.setObjectName("depend_group")
        self.gridLayout_2.addWidget(self.depend_group, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.downloads_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.downloads_label.setText("")
        self.downloads_label.setObjectName("downloads_label")
        self.gridLayout_3.addWidget(self.downloads_label, 0, 1, 1, 1)
        self.date_published_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.date_published_label.setText("")
        self.date_published_label.setObjectName("date_published_label")
        self.gridLayout_3.addWidget(self.date_published_label, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.file_group = GroupHeaderCardWidget(parent=self.scrollAreaWidgetContents)
        self.file_group.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.file_group.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.file_group.setObjectName("file_group")
        self.gridLayout_2.addWidget(self.file_group, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(ModrinthVersion)
        QtCore.QMetaObject.connectSlotsByName(ModrinthVersion)

    def retranslateUi(self, ModrinthVersion):
        _translate = QtCore.QCoreApplication.translate
        ModrinthVersion.setWindowTitle(_translate("ModrinthVersion", "ModrinthVersion"))
        self.label.setText(_translate("ModrinthVersion", "下载量:"))
        self.label_2.setText(_translate("ModrinthVersion", "发布日期:"))
from qfluentwidgets import GroupHeaderCardWidget, HeaderCardWidget, ScrollArea
