# Form implementation generated from reading ui file 'd:\Codes\FMCL\functions\resourcedownloader\resource_downloader.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResourceDownloader(object):
    def setupUi(self, ResourceDownloader):
        ResourceDownloader.setObjectName("ResourceDownloader")
        ResourceDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ResourceDownloader)
        self.gridLayout.setObjectName("gridLayout")
        self.searcher_tab = SegmentedWidget(parent=ResourceDownloader)
        self.searcher_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.searcher_tab.setObjectName("searcher_tab")
        self.gridLayout.addWidget(self.searcher_tab, 2, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(parent=ResourceDownloader)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.searcher_stack = QtWidgets.QStackedWidget(parent=self.splitter)
        self.searcher_stack.setObjectName("searcher_stack")
        self.search_results = ListWidget(parent=self.splitter)
        self.search_results.setObjectName("search_results")
        self.gridLayout.addWidget(self.splitter, 3, 0, 1, 2)
        self.search_input = SearchLineEdit(parent=ResourceDownloader)
        self.search_input.setObjectName("search_input")
        self.gridLayout.addWidget(self.search_input, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modrinth_enable = CheckBox(parent=ResourceDownloader)
        self.modrinth_enable.setChecked(True)
        self.modrinth_enable.setObjectName("modrinth_enable")
        self.horizontalLayout.addWidget(self.modrinth_enable)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)

        self.retranslateUi(ResourceDownloader)
        QtCore.QMetaObject.connectSlotsByName(ResourceDownloader)

    def retranslateUi(self, ResourceDownloader):
        _translate = QtCore.QCoreApplication.translate
        ResourceDownloader.setWindowTitle(_translate("ResourceDownloader", "资源下载器"))
        self.modrinth_enable.setText(_translate("ResourceDownloader", "Modrinth"))
from qfluentwidgets import CheckBox, ListWidget, SearchLineEdit, SegmentedWidget
